export const episodes = [
    // --- MSK / SPORTS ---
    { title: "MSK: Shoulder 1", url: "./audio/MSK_Shoulder_1.m4a", category: "MSK/Sports" },
    { title: "MSK: Shoulder 2", url: "./audio/MSK_Shoulder_2.m4a", category: "MSK/Sports" },
    { title: "MSK: Shoulder 3", url: "./audio/MSK_Shoulder_3.m4a", category: "MSK/Sports" },
    { title: "MSK: Shoulder 4", url: "./audio/MSK_Shoulder_4.m4a", category: "MSK/Sports" },
    { title: "MSK: Elbow 1", url: "./audio/MSK_Elbow_1.m4a", category: "MSK/Sports" },
    { title: "MSK: Elbow 2", url: "./audio/MSK_Elbow_2.m4a", category: "MSK/Sports" },
    { title: "MSK: Wrist", url: "./audio/MSK_Wrist.m4a", category: "MSK/Sports" },
    { title: "MSK: Hand", url: "./audio/MSK_Hand.m4a", category: "MSK/Sports" },
    { title: "MSK: Hip 1", url: "./audio/MSK_Hip_1.m4a", category: "MSK/Sports" },
    { title: "MSK: Hip 2", url: "./audio/MSK_Hip_2.m4a", category: "MSK/Sports" },
    { title: "MSK: Hip 3", url: "./audio/MSK_Hip_3.m4a", category: "MSK/Sports" },
    { title: "MSK: Knee 1", url: "./audio/MSK_Knee_1.m4a", category: "MSK/Sports" },
    { title: "MSK: Knee 2", url: "./audio/MSK_Knee_2.m4a", category: "MSK/Sports" },
    { title: "MSK: Knee 3", url: "./audio/MSK_Knee_3.m4a", category: "MSK/Sports" },
    { title: "MSK: Ankle 1", url: "./audio/MSK_Ankle_1.m4a", category: "MSK/Sports" },
    { title: "MSK: Ankle 2", url: "./audio/MSK_Ankle_2.m4a", category: "MSK/Sports" },
    { title: "MSK: Foot", url: "./audio/MSK_Foot.m4a", category: "MSK/Sports" },
    { title: "MSK: Lower Leg", url: "./audio/MSK_Lower_Leg.m4a", category: "MSK/Sports" },
    { title: "MSK: Spine 1", url: "./audio/MSK_Spine_1.m4a", category: "MSK/Sports" },
    { title: "MSK: Spine 2", url: "./audio/MSK_Spine_2.m4a", category: "MSK/Sports" },
    { title: "MSK: Spine 3", url: "./audio/MSK_Spine_3.m4a", category: "MSK/Sports" },
    { title: "MSK: Spine 4", url: "./audio/MSK_Spine_4.m4a", category: "MSK/Sports" },
    { title: "MSK: Spine 5", url: "./audio/MSK_Spine_5.m4a", category: "MSK/Sports" },
    { title: "MSK: Spine 6", url: "./audio/MSK_Spine_6.m4a", category: "MSK/Sports" },

    // --- NEUROREHABILITATION ---
    { title: "Multiple Sclerosis 1", url: "./audio/MS_1.m4a", category: "Neuro Rehab" },
    { title: "Multiple Sclerosis 2", url: "./audio/MS_2.m4a", category: "Neuro Rehab" },
    { title: "Stroke 1", url: "./audio/CVA_1.m4a", category: "Neuro Rehab" },
    { title: "Stroke 2", url: "./audio/CVA_2.m4a", category: "Neuro Rehab" },
    { title: "Stroke 3", url: "./audio/CVA_3.m4a", category: "Neuro Rehab" },
    { title: "Stroke 4", url: "./audio/CVA_4.m4a", category: "Neuro Rehab" },
    { title: "Stroke 5", url: "./audio/CVA_5.m4a", category: "Neuro Rehab" },
    { title: "Stroke 6", url: "./audio/CVA_6.m4a", category: "Neuro Rehab" },
    { title: "TBI 1", url: "./audio/TBI_1.m4a", category: "Neuro Rehab" },
    { title: "TBI 2", url: "./audio/TBI_2.m4a", category: "Neuro Rehab" },
    { title: "TBI 3", url: "./audio/TBI_3.m4a", category: "Neuro Rehab" },
    { title: "TBI 4", url: "./audio/TBI_4.m4a", category: "Neuro Rehab" },
    { title: "TBI 5", url: "./audio/TBI_5.m4a", category: "Neuro Rehab" },
    { title: "TBI 6", url: "./audio/TBI_6.m4a", category: "Neuro Rehab" },
    { title: "SCI 1", url: "./audio/SCI_1.m4a", category: "Neuro Rehab" },
    { title: "SCI 2", url: "./audio/SCI_2.m4a", category: "Neuro Rehab" },
    { title: "SCI 3", url: "./audio/SCI_3.m4a", category: "Neuro Rehab" },
    { title: "SCI 4", url: "./audio/SCI_4.m4a", category: "Neuro Rehab" },
    { title: "SCI 5", url: "./audio/SCI_5.m4a", category: "Neuro Rehab" },
    { title: "SCI 6", url: "./audio/SCI_6.m4a", category: "Neuro Rehab" },
    { title: "SCI 7", url: "./audio/SCI_7.m4a", category: "Neuro Rehab" },
    { title: "SCI 8", url: "./audio/SCI_8.m4a", category: "Neuro Rehab" },
    { title: "SCI 9", url: "./audio/SCI_9.m4a", category: "Neuro Rehab" },
    { title: "SCI 10", url: "./audio/SCI_10.m4a", category: "Neuro Rehab" },
    { title: "Spasticity 1", url: "./audio/Spasticity_1.m4a", category: "Neuro Rehab" },
    { title: "Spasticity 2", url: "./audio/Spasticity_2.m4a", category: "Neuro Rehab" },
    { title: "Spasticity 3", url: "./audio/Spasticity_3.m4a", category: "Neuro Rehab" },

    // --- EDX ---
    { title: "EDX 1", url: "./audio/EDX_1.m4a", category: "EDX" },
    { title: "EDX 2", url: "./audio/EDX_2.m4a", category: "EDX" },
    { title: "EDX 3", url: "./audio/EDX_3.m4a", category: "EDX" },
    { title: "EDX 4", url: "./audio/EDX_4.m4a", category: "EDX" },
    { title: "EDX 5", url: "./audio/EDX_5.m4a", category: "EDX" },
    { title: "EDX 6", url: "./audio/EDX_6.m4a", category: "EDX" },
    { title: "EDX 7", url: "./audio/EDX_7.m4a", category: "EDX" },
    { title: "EDX 8", url: "./audio/EDX_8.m4a", category: "EDX" },
    { title: "EDX 9", url: "./audio/EDX_9.m4a", category: "EDX" },
    { title: "EDX 10", url: "./audio/EDX_10.m4a", category: "EDX" },
    { title: "EDX 11", url: "./audio/EDX_11.m4a", category: "EDX" },
    { title: "EDX 12", url: "./audio/EDX_12.m4a", category: "EDX" },
    { title: "EDX 13", url: "./audio/EDX_13.m4a", category: "EDX" },
    { title: "EDX 14", url: "./audio/EDX_14.m4a", category: "EDX" },
    { title: "EDX 15", url: "./audio/EDX_15.m4a", category: "EDX" },

    // --- PEDIATRICS ---
    { title: "Peds 1", url: "./audio/Peds_1.m4a", category: "Pediatrics" },
    { title: "Peds 2", url: "./audio/Peds_2.m4a", category: "Pediatrics" },
    { title: "Peds 3", url: "./audio/Peds_3.m4a", category: "Pediatrics" },
    { title: "Peds 4", url: "./audio/Peds_4.m4a", category: "Pediatrics" },
    { title: "Peds 5", url: "./audio/Peds_5.m4a", category: "Pediatrics" },
    { title: "Peds 6", url: "./audio/Peds_6.m4a", category: "Pediatrics" },
    { title: "Peds 7", url: "./audio/Peds_7.m4a", category: "Pediatrics" },
    { title: "Peds 8", url: "./audio/Peds_8.m4a", category: "Pediatrics" },
    { title: "Peds 9", url: "./audio/Peds_9.m4a", category: "Pediatrics" },
    { title: "Peds 10", url: "./audio/Peds_10.m4a", category: "Pediatrics" },
    { title: "Peds 11", url: "./audio/Peds_11.m4a", category: "Pediatrics" },

    // --- P&O ---
    { title: "P&O 1", url: "./audio/P&O_1.m4a", category: "P&O" },
    { title: "P&O 2", url: "./audio/P&O_2.m4a", category: "P&O" },
    { title: "P&O 3", url: "./audio/P&O_3.m4a", category: "P&O" },
    { title: "P&O 4", url: "./audio/P&O_4.m4a", category: "P&O" },
    { title: "P&O 5", url: "./audio/P&O_5.m4a", category: "P&O" },
    { title: "P&O 6", url: "./audio/P&O_6.m4a", category: "P&O" },
    { title: "P&O 7", url: "./audio/P&O_7.m4a", category: "P&O" },
    { title: "P&O 8", url: "./audio/P&O_8.m4a", category: "P&O" },
    { title: "P&O 9", url: "./audio/P&O_9.m4a", category: "P&O" },
    { title: "P&O 10", url: "./audio/P&O_10.m4a", category: "P&O" },
    { title: "Wheelchair 1", url: "./audio/Wheelchair_1.m4a", category: "P&O" },
    { title: "Wheelchair 2", url: "./audio/Wheelchair_2.m4a", category: "P&O" },

    // --- SPECIALIZED CLINICAL AREAS ---
    { title: "Burns 1", url: "./audio/Burns_1.m4a", category: "Specialized Rehab" },
    { title: "Burns 2", url: "./audio/Burns_2.m4a", category: "Specialized Rehab" },
    { title: "Cancer Rehab 1", url: "./audio/Cancer_Rehab_1.m4a", category: "Specialized Rehab" },
    { title: "Cancer Rehab 2", url: "./audio/Cancer_Rehab_2.m4a", category: "Specialized Rehab" },
    { title: "Cancer Rehab 3", url: "./audio/Cancer_Rehab_3.m4a", category: "Specialized Rehab" },
    { title: "Cardiac Rehab 1", url: "./audio/Cardiac_Rehab_1.m4a", category: "Specialized Rehab" },
    { title: "Cardiac Rehab 2", url: "./audio/Cardiac_Rehab_2.m4a", category: "Specialized Rehab" },
    { title: "Cardiac Rehab 3", url: "./audio/Cardiac_Rehab_3.m4a", category: "Specialized Rehab" },
    { title: "Cardiac Rehab 4", url: "./audio/Cardiac_Rehab_4.m4a", category: "Specialized Rehab" },
    { title: "Osteoporosis 1", url: "./audio/Osteoporosis_1.m4a", category: "Specialized Rehab" },
    { title: "Osteoporosis 2", url: "./audio/Osteoporosis_2.m4a", category: "Specialized Rehab" },
    { title: "Pain 1", url: "./audio/Pain_1.m4a", category: "Specialized Rehab" },
    { title: "Pain 2", url: "./audio/Pain_2.m4a", category: "Specialized Rehab" },
    { title: "Pain 3", url: "./audio/Pain_3.m4a", category: "Specialized Rehab" },
    { title: "Pain 4", url: "./audio/Pain_4.m4a", category: "Specialized Rehab" },
    { title: "Pulmonary 1", url: "./audio/Pulm_1.m4a", category: "Specialized Rehab" },
    { title: "Pulmonary 2", url: "./audio/Pulm_2.m4a", category: "Specialized Rehab" },
    { title: "Pulmonary 3", url: "./audio/Pulm_3.m4a", category: "Specialized Rehab" },
    { title: "Rheum 1", url: "./audio/Rheum_1.m4a", category: "Specialized Rehab" },
    { title: "Rheum 2", url: "./audio/Rheum_2.m4a", category: "Specialized Rehab" },
    { title: "Rheum 3", url: "./audio/Rheum_3.m4a", category: "Specialized Rehab" },
    { title: "Rheum 4", url: "./audio/Rheum_4.m4a", category: "Specialized Rehab" },
    { title: "Rheum 5", url: "./audio/Rheum_5.m4a", category: "Specialized Rehab" },
    { title: "Rheum 6", url: "./audio/Rheum_6.m4a", category: "Specialized Rehab" },

    // --- FOUNDATIONS ---
    { title: "Bioethics", url: "./audio/Bioethics.m4a", category: "Foundations" },
    { title: "Biostats", url: "./audio/Biostats.m4a", category: "Foundations" },
    { title: "Physical Modalities 1", url: "./audio/Physical_Modalities_1.m4a", category: "Foundations" },
    { title: "Physical Modalities 2", url: "./audio/Physical_Modalities_2.m4a", category: "Foundations" },
    { title: "Physical Modalities 3", url: "./audio/Physical_Modalities_3.m4a", category: "Foundations" },
    { title: "Physical Modalities 4", url: "./audio/Physical_Modalities_4.m4a", category: "Foundations" },
    { title: "The Board Exam", url: "./audio/The_Board_Exam.m4a", category: "Foundations" }
];
