export const episodes = [
    // --- MSK / SPORTS ---
    { title: "Musculoskeletal: Shoulder 1", url: "./audio/MSK_Shoulder_1.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Shoulder 2", url: "./audio/MSK_Shoulder_2.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Shoulder 3", url: "./audio/MSK_Shoulder_3.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Shoulder 4", url: "./audio/MSK_Shoulder_4.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Elbow 1", url: "./audio/MSK_Elbow_1.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Elbow 2", url: "./audio/MSK_Elbow_2.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Wrist", url: "./audio/MSK_Wrist.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Hand", url: "./audio/MSK_Hand.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Hip 1", url: "./audio/MSK_Hip_1.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Hip 2", url: "./audio/MSK_Hip_2.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Hip 3", url: "./audio/MSK_Hip_3.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Knee 1", url: "./audio/MSK_Knee_1.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Knee 2", url: "./audio/MSK_Knee_2.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Knee 3", url: "./audio/MSK_Knee_3.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Ankle 1", url: "./audio/MSK_Ankle_1.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Ankle 2", url: "./audio/MSK_Ankle_2.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Foot", url: "./audio/MSK_Foot.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Lower Leg", url: "./audio/MSK_Lower_Leg.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Spine 1", url: "./audio/MSK_Spine_1.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Spine 2", url: "./audio/MSK_Spine_2.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Spine 3", url: "./audio/MSK_Spine_3.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Spine 4", url: "./audio/MSK_Spine_4.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Spine 5", url: "./audio/MSK_Spine_5.m4a", category: "MSK/Sports" },
    { title: "Musculoskeletal: Spine 6", url: "./audio/MSK_Spine_6.m4a", category: "MSK/Sports" },

    // --- NEUROREHABILITATION ---
    { title: "Multiple Sclerosis 1", url: "./audio/MS_1.m4a", category: "Neuro Rehab" },
    { title: "Multiple Sclerosis 2", url: "./audio/MS_2.m4a", category: "Neuro Rehab" },
    { title: "Stroke 1", url: "./audio/CVA_1.m4a", category: "Neuro Rehab" },
    { title: "Stroke 2", url: "./audio/CVA_2.m4a", category: "Neuro Rehab" },
    { title: "Stroke 3", url: "./audio/CVA_3.m4a", category: "Neuro Rehab" },
    { title: "Stroke 4", url: "./audio/CVA_4.m4a", category: "Neuro Rehab" },
    { title: "Stroke 5", url: "./audio/CVA_5.m4a", category: "Neuro Rehab" },
    { title: "Stroke 6", url: "./audio/CVA_6.m4a", category: "Neuro Rehab" },
    { title: "Traumatic Brain Injury 1", url: "./audio/TBI_1.m4a", category: "Neuro Rehab" },
    { title: "Traumatic Brain Injury 2", url: "./audio/TBI_2.m4a", category: "Neuro Rehab" },
    { title: "Traumatic Brain Injury 3", url: "./audio/TBI_3.m4a", category: "Neuro Rehab" },
    { title: "Traumatic Brain Injury 4", url: "./audio/TBI_4.m4a", category: "Neuro Rehab" },
    { title: "Traumatic Brain Injury 5", url: "./audio/TBI_5.m4a", category: "Neuro Rehab" },
    { title: "Traumatic Brain Injury 6", url: "./audio/TBI_6.m4a", category: "Neuro Rehab" },
    { title: "Spinal Cord Injury 1", url: "./audio/SCI_1.m4a", category: "Neuro Rehab" },
    { title: "Spinal Cord Injury 2", url: "./audio/SCI_2.m4a", category: "Neuro Rehab" },
    { title: "Spinal Cord Injury 3", url: "./audio/SCI_3.m4a", category: "Neuro Rehab" },
    { title: "Spinal Cord Injury 4", url: "./audio/SCI_4.m4a", category: "Neuro Rehab" },
    { title: "Spinal Cord Injury 5", url: "./audio/SCI_5.m4a", category: "Neuro Rehab" },
    { title: "Spinal Cord Injury 6", url: "./audio/SCI_6.m4a", category: "Neuro Rehab" },
    { title: "Spinal Cord Injury 7", url: "./audio/SCI_7.m4a", category: "Neuro Rehab" },
    { title: "Spinal Cord Injury 8", url: "./audio/SCI_8.m4a", category: "Neuro Rehab" },
    { title: "Spinal Cord Injury 9", url: "./audio/SCI_9.m4a", category: "Neuro Rehab" },
    { title: "Spinal Cord Injury 10", url: "./audio/SCI_10.m4a", category: "Neuro Rehab" },
    { title: "Spasticity 1", url: "./audio/Spasticity_1.m4a", category: "Neuro Rehab" },
    { title: "Spasticity 2", url: "./audio/Spasticity_2.m4a", category: "Neuro Rehab" },
    { title: "Spasticity 3", url: "./audio/Spasticity_3.m4a", category: "Neuro Rehab" },

    // --- EDX ---
    { title: "Electrodiagnostic 1", url: "./audio/EDX_1.m4a", category: "EDX" },
    { title: "Electrodiagnostic 2", url: "./audio/EDX_2.m4a", category: "EDX" },
    { title: "Electrodiagnostic 3", url: "./audio/EDX_3.m4a", category: "EDX" },
    { title: "Electrodiagnostic 4", url: "./audio/EDX_4.m4a", category: "EDX" },
    { title: "Electrodiagnostic 5", url: "./audio/EDX_5.m4a", category: "EDX" },
    { title: "Electrodiagnostic 6", url: "./audio/EDX_6.m4a", category: "EDX" },
    { title: "Electrodiagnostic 7", url: "./audio/EDX_7.m4a", category: "EDX" },
    { title: "Electrodiagnostic 8", url: "./audio/EDX_8.m4a", category: "EDX" },
    { title: "Electrodiagnostic 9", url: "./audio/EDX_9.m4a", category: "EDX" },
    { title: "Electrodiagnostic 10", url: "./audio/EDX_10.m4a", category: "EDX" },
    { title: "Electrodiagnostic 11", url: "./audio/EDX_11.m4a", category: "EDX" },
    { title: "Electrodiagnostic 12", url: "./audio/EDX_12.m4a", category: "EDX" },
    { title: "Electrodiagnostic 13", url: "./audio/EDX_13.m4a", category: "EDX" },
    { title: "Electrodiagnostic 14", url: "./audio/EDX_14.m4a", category: "EDX" },
    { title: "Electrodiagnostic 15", url: "./audio/EDX_15.m4a", category: "EDX" },

    // --- PEDIATRICS ---
    { title: "Pediatrics 1", url: "./audio/Peds_1.m4a", category: "Pediatrics" },
    { title: "Pediatrics 2", url: "./audio/Peds_2.m4a", category: "Pediatrics" },
    { title: "Pediatrics 3", url: "./audio/Peds_3.m4a", category: "Pediatrics" },
    { title: "Pediatrics 4", url: "./audio/Peds_4.m4a", category: "Pediatrics" },
    { title: "Pediatrics 5", url: "./audio/Peds_5.m4a", category: "Pediatrics" },
    { title: "Pediatrics 6", url: "./audio/Peds_6.m4a", category: "Pediatrics" },
    { title: "Pediatrics 7", url: "./audio/Peds_7.m4a", category: "Pediatrics" },
    { title: "Pediatrics 8", url: "./audio/Peds_8.m4a", category: "Pediatrics" },
    { title: "Pediatrics 9", url: "./audio/Peds_9.m4a", category: "Pediatrics" },
    { title: "Pediatrics 10", url: "./audio/Peds_10.m4a", category: "Pediatrics" },
    { title: "Pediatrics 11", url: "./audio/Peds_11.m4a", category: "Pediatrics" },

    // --- P&O ---
    { title: "Prosthetics & Orthotics 1", url: "./audio/P&O_1.m4a", category: "P&O" },
    { title: "Prosthetics & Orthotics 2", url: "./audio/P&O_2.m4a", category: "P&O" },
    { title: "Prosthetics & Orthotics 3", url: "./audio/P&O_3.m4a", category: "P&O" },
    { title: "Prosthetics & Orthotics 4", url: "./audio/P&O_4.m4a", category: "P&O" },
    { title: "Prosthetics & Orthotics 5", url: "./audio/P&O_5.m4a", category: "P&O" },
    { title: "Prosthetics & Orthotics 6", url: "./audio/P&O_6.m4a", category: "P&O" },
    { title: "Prosthetics & Orthotics 7", url: "./audio/P&O_7.m4a", category: "P&O" },
    { title: "Prosthetics & Orthotics 8", url: "./audio/P&O_8.m4a", category: "P&O" },
    { title: "Prosthetics & Orthotics 9", url: "./audio/P&O_9.m4a", category: "P&O" },
    { title: "Prosthetics & Orthotics 10", url: "./audio/P&O_10.m4a", category: "P&O" },
    { title: "Wheelchair 1", url: "./audio/Wheelchair_1.m4a", category: "P&O" },
    { title: "Wheelchair 2", url: "./audio/Wheelchair_2.m4a", category: "P&O" },

    // --- SPECIALIZED CLINICAL AREAS ---
    { title: "Burns 1", url: "./audio/Burns_1.m4a", category: "Specialized Rehab" },
    { title: "Burns 2", url: "./audio/Burns_2.m4a", category: "Specialized Rehab" },
    { title: "Cancer Rehab 1", url: "./audio/Cancer_Rehab_1.m4a", category: "Specialized Rehab" },
    { title: "Cancer Rehab 2", url: "./audio/Cancer_Rehab_2.m4a", category: "Specialized Rehab" },
    { title: "Cancer Rehab 3", url: "./audio/Cancer_Rehab_3.m4a", category: "Specialized Rehab" },
    { title: "Cardiac Rehab 1", url: "./audio/Cardiac_Rehab_1.m4a", category: "Specialized Rehab" },
    { title: "Cardiac Rehab 2", url: "./audio/Cardiac_Rehab_2.m4a", category: "Specialized Rehab" },
    { title: "Cardiac Rehab 3", url: "./audio/Cardiac_Rehab_3.m4a", category: "Specialized Rehab" },
    { title: "Cardiac Rehab 4", url: "./audio/Cardiac_Rehab_4.m4a", category: "Specialized Rehab" },
    { title: "Osteoporosis 1", url: "./audio/Osteoporosis_1.m4a", category: "Specialized Rehab" },
    { title: "Osteoporosis 2", url: "./audio/Osteoporosis_2.m4a", category: "Specialized Rehab" },
    { title: "Pain 1", url: "./audio/Pain_1.m4a", category: "Specialized Rehab" },
    { title: "Pain 2", url: "./audio/Pain_2.m4a", category: "Specialized Rehab" },
    { title: "Pain 3", url: "./audio/Pain_3.m4a", category: "Specialized Rehab" },
    { title: "Pain 4", url: "./audio/Pain_4.m4a", category: "Specialized Rehab" },
    { title: "Pulmonary 1", url: "./audio/Pulm_1.m4a", category: "Specialized Rehab" },
    { title: "Pulmonary 2", url: "./audio/Pulm_2.m4a", category: "Specialized Rehab" },
    { title: "Pulmonary 3", url: "./audio/Pulm_3.m4a", category: "Specialized Rehab" },
    { title: "Rheumatology 1", url: "./audio/Rheum_1.m4a", category: "Specialized Rehab" },
    { title: "Rheumatology 2", url: "./audio/Rheum_2.m4a", category: "Specialized Rehab" },
    { title: "Rheumatology 3", url: "./audio/Rheum_3.m4a", category: "Specialized Rehab" },
    { title: "Rheumatology 4", url: "./audio/Rheum_4.m4a", category: "Specialized Rehab" },
    { title: "Rheumatology 5", url: "./audio/Rheum_5.m4a", category: "Specialized Rehab" },
    { title: "Rheumatology 6", url: "./audio/Rheum_6.m4a", category: "Specialized Rehab" },

    // --- FOUNDATIONS ---
    { title: "Bioethics", url: "./audio/Bioethics.m4a", category: "Foundations" },
    { title: "Biostatistics", url: "./audio/Biostats.m4a", category: "Foundations" },
    { title: "Physical Modalities 1", url: "./audio/Physical_Modalities_1.m4a", category: "Foundations" },
    { title: "Physical Modalities 2", url: "./audio/Physical_Modalities_2.m4a", category: "Foundations" },
    { title: "Physical Modalities 3", url: "./audio/Physical_Modalities_3.m4a", category: "Foundations" },
    { title: "Physical Modalities 4", url: "./audio/Physical_Modalities_4.m4a", category: "Foundations" },
    { title: "The Board Exam", url: "./audio/The_Board_Exam.m4a", category: "Foundations" }
];
